name: book
channels:
  - daytum
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.0.0
  - docopt=0.6.2
  - intake=0.5.4
  - intake-parquet=0.2.3
  - intake-sql=0.2.0
  - data=0.0.35
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.8.2
  - scipy=1.4.1
  - matplotlib=3.2.1
  - sympy=1.5.1
  - seaborn=0.10.0
  - panel==0.5.1
  - pip:
    - jupyter-book==0.6.4
