name: book
channels:
  - daytum
  - conda-forge
  - defaults
dependencies:
  - bokeh=2.0.0
  - data=0.0.35=3
  - hvplot=0.5.2
  - matplotlib=3.2.1
  - notebook=6.0.3
  - numpy=1.18.1
  - pandas=1.0.3
  - panel=0.9.3
  - python=3.8.2
  - scipy=1.4.1
  - seaborn=0.10.0
  - sympy=1.5.1
  - pip=20.0.2
  - docopt=0.6.2
  - pip:
    - jupyter-book==0.6.4
